[package]
name = "rustorm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Manage the hosts in ~/.ssh/config from the command line"

[[bin]]
name = "rustorm"
path = "src/main.rs"

[dependencies]
rustorm-core = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
serde_json = { workspace = true }
